### ISSUE TITLE
Sending a message containing `<`, `>`, `(`, `)` cause `CommonRequestException` 

### ISSUE THREAD

**Issue by JellyBrick** [InsanusMokrassar/TelegramBotAPI#710]
# error log

```java
dev.inmo.tgbotapi.bot.exceptions.CommonRequestException: Can't get result object from {"ok":false,"error_code":400,"description":"Bad Request: can't parse entities: Character '>' is reserved and must be escaped with the preceding '\\'"}
        at dev.inmo.tgbotapi.bot.exceptions.RequestExceptionKt.newRequestException(RequestException.kt:37)
        at dev.inmo.tgbotapi.bot.exceptions.RequestExceptionKt.newRequestException$default(RequestException.kt:9)
        at dev.inmo.tgbotapi.bot.ktor.base.AbstractRequestCallFactory$makeCall$3$1.invokeSuspend(AbstractRequestCallFactory.kt:63)
        at dev.inmo.tgbotapi.bot.ktor.base.AbstractRequestCallFactory$makeCall$3$1.invoke(AbstractRequestCallFactory.kt)
        at dev.inmo.tgbotapi.bot.ktor.base.AbstractRequestCallFactory$makeCall$3$1.invoke(AbstractRequestCallFactory.kt)
        at dev.inmo.tgbotapi.bot.ktor.base.AbstractRequestCallFactory$makeCall$lambda$3$$inlined$safelyWithResult$1.invokeSuspend(HandleSafely.kt:122)
        at dev.inmo.tgbotapi.bot.ktor.base.AbstractRequestCallFactory$makeCall$lambda$3$$inlined$safelyWithResult$1.invoke(HandleSafely.kt)
        at dev.inmo.tgbotapi.bot.ktor.base.AbstractRequestCallFactory$makeCall$lambda$3$$inlined$safelyWithResult$1.invoke(HandleSafely.kt)
        at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
        at kotlinx.coroutines.SupervisorKt.supervisorScope(Supervisor.kt:61)
        at dev.inmo.tgbotapi.bot.ktor.base.AbstractRequestCallFactory.makeCall$suspendImpl(AbstractRequestCallFactory.kt:105)
        at dev.inmo.tgbotapi.bot.ktor.base.AbstractRequestCallFactory$makeCall$1.invokeSuspend(AbstractRequestCallFactory.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```

# message

`(Telegram HTML)`

# code

```kotlin
import dev.inmo.tgbotapi.extensions.api.send.reply

BehaviourContext.reply(TextMessage, "(Telegram HTML)", MarkdownV2ParseMode, allowSendingWithoutReply = true)
```

**Comment by JellyBrick** [comment]
https://stackoverflow.com/a/71313944/6544084

It seems like it should provide the auto-escaping feature in this API.

**Comment by InsanusMokrassar** [comment]
It is expected that in case you are preparing m2 text for sending you will escape it with something like [escapeMarkdownV2Common](https://tgbotapi.inmo.dev/docs/dev.inmo.tgbotapi.utils.extensions/escape-markdown-v2-common.html) due to the fact that I don't know where you have added a link (syntax \[\]\(\)) or where you are sending a sample which
