### ISSUE TITLE
Error in requestExecutor.startGettingOfUpdates

### ISSUE THREAD

**Issue by Djaler** [InsanusMokrassar/TelegramBotAPI#76]
```
Exception in thread "DefaultDispatcher-worker-1" kotlinx.coroutines.CoroutinesInternalError: Fatal exception in coroutines machinery for DispatchedContinuation[DefaultDispatcher, Continuation at com.github.insanusmokrassar.TelegramBotAPI.extensions.api.updates.UpdatesPollingKt$startGettingOfUpdates$1.invokeSuspend(UpdatesPolling.kt:28)@1ab61e5a]. Please read KDoc to 'handleFatalException' method and report this incident to maintainers
  at kotlinx.coroutines.DispatchedTask.handleFatalException$kotlinx_coroutines_core(DispatchedTask.kt:93)
  at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:64)
  at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:561)
  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:727)
  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:667)
  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:655)
Caused by: java.lang.ClassCastException: kotlin.coroutines.jvm.internal.CompletedContinuation cannot be cast to kotlinx.coroutines.DispatchedContinuation
  at kotlinx.coroutines.CoroutineDispatcher.releaseInterceptedContinuation(CoroutineDispatcher.kt:94)
  at kotlin.coroutines.jvm.internal.ContinuationImpl.releaseIntercepted(ContinuationImpl.kt:118)
  at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:39)
  at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
  ... 4 more
```

**Comment by InsanusMokrassar** [comment]
Can you, please, send the configuration of your dependenies?

**Comment by Djaler** [comment]
Fixed after update kotlin and ktor
