### ISSUE TITLE
java.lang.IllegalArgumentException: Can't find correct serializer for inline button

### ISSUE THREAD

**Issue by Djaler** [InsanusMokrassar/TelegramBotAPI#79]
```
java.lang.IllegalArgumentException: Can't find correct serializer for inline button serialized as {"text":"Играть в Math Battle","callback_game":{}}
at com.github.insanusmokrassar.TelegramBotAPI.types.buttons.InlineKeyboardButtons.InlineKeyboardButtonSerializer.resolveSerializer(InlineKeyboardButtonSerializer.kt:23)
at com.github.insanusmokrassar.TelegramBotAPI.types.buttons.InlineKeyboardButtons.InlineKeyboardButtonSerializer.deserialize(InlineKeyboardButtonSerializer.kt:30)
at com.github.insanusmokrassar.TelegramBotAPI.types.buttons.InlineKeyboardButtons.InlineKeyboardButtonSerializer.deserialize(InlineKeyboardButtonSerializer.kt:9)
```

Full update content:
```
{
   "update_id":84386544,
   "message":{
      "message_id":15118,
      "from":{
         "id":733446234,
         "is_bot":false,
         "first_name":"sᴇᴍ",
         "username":"Dilonlu"
      },
      "chat":{
         "id":-1001431988625,
         "title":"Friends 🤐😏😌😏",
         "type":"supergroup"
      },
      "date":1586624397,
      "game":{
         "title":"Math Battle",
         "description":"Show your math skills! How high can you score?",
         "photo":[
            {
               "file_id":"AgACAgEAAxUAAV6R943SYY9bcDEUK9zQbKhhjpMUAAI7tzEb43gEAAHNE0POhQGvF_3x5y8ABAEAAwIAA3MAA4__AAIYBA",
               "file_unique_id":"AQAD_fHnLwAEj_8AAg",
               "file_size":872,
               "width":90,
               "height":51
            },
            {
               "file_id":"AgACAgEAAxUAAV6R943SYY9bcDEUK9zQbKhhjpMUAAI7tzEb43gEAAHNE0POhQGvF_3x5y8ABAEAAwIAA20AA5D_AAIYBA",
               "file_unique_id":"AQAD_fHnLwAEkP8AAg",
               "file_size":9962,
               "width":320,
               "height":180
            },
            {
               "file_id":"AgACAgEAAxUAAV6R943SYY9bcDEUK9zQbKhhjpMUAAI7tzEb43gEAAHNE0POhQGvF_3x5y8ABAEAAwIAA3gAA47_AAIYBA",
               "file_unique_id":"AQAD_fHnLwAEjv8AAg",
               "file_size":19899,
               "width":640,
               "height":360
            }
         ]
      },
      "reply_markup":{
         "inline_keyboard":[
            [
               {
                  "text":"Играть в Math Battle",
                  "callback_game":{

                  }
               }
            ]
         ]
      }
   }
}
```

**Comment by InsanusMokrassar** [comment]
Fixed in [0.26.3](https://github.com/InsanusMokrassar/TelegramBotAPI/blob/master/CHANGELOG.md#0263)
