### ISSUE TITLE
An operation is not implemented in CallbackGame

### ISSUE THREAD

**Issue by Djaler** [InsanusMokrassar/TelegramBotAPI#82]
```
2020-04-22T05:54:09.034066+00:00 app[web.1]: kotlin.NotImplementedError: An operation is not implemented.
2020-04-22T05:54:09.034067+00:00 app[web.1]: 	at com.github.insanusmokrassar.TelegramBotAPI.types.games.CallbackGame.<init>(CallbackGame.kt:8)
2020-04-22T05:54:09.034068+00:00 app[web.1]: 	at com.github.insanusmokrassar.TelegramBotAPI.types.games.CallbackGame$$serializer.deserialize(CallbackGame.kt)
2020-04-22T05:54:09.034068+00:00 app[web.1]: 	at com.github.insanusmokrassar.TelegramBotAPI.types.games.CallbackGame$$serializer.deserialize(CallbackGame.kt:6)
2020-04-22T05:54:09.034069+00:00 app[web.1]: 	at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:52)
2020-04-22T05:54:09.034069+00:00 app[web.1]: 	at kotlinx.serialization.json.internal.AbstractJsonTreeInput.decodeSerializableValue(TreeJsonInput.kt:44)
2020-04-22T05:54:09.034070+00:00 app[web.1]: 	at kotlinx.serialization.internal.TaggedDecoder$decodeSerializableElement$1.invoke(Tagged.kt:230)
2020-04-22T05:54:09.034070+00:00 app[web.1]: 	at kotlinx.serialization.internal.TaggedDecoder.tagBlock(Tagged.kt:243)
2020-04-22T05:54:09.034071+00:00 app[web.1]: 	at kotlinx.serialization.internal.TaggedDecoder.decodeSerializableElement(Tagged.kt:230)
2020-04-22T05:54:09.034072+00:00 app[web.1]: 	at com.github.insanusmokrassar.TelegramBotAPI.types.buttons.InlineKeyboardButtons.CallbackGameInlineKeyboardButton$$serializer.deserialize(InlineKeyboardButton.kt)
2020-04-22T05:54:09.034073+00:00 app[web.1]: 	at com.github.insanusmokrassar.TelegramBotAPI.types.buttons.InlineKeyboardButtons.CallbackGameInlineKeyboardButton$$serializer.deserialize(InlineKeyboardButton.kt:37)
2020-04-22T05:54:09.034073+00:00 app[web.1]: 	at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:52)
2020-04-22T05:54:09.034074+00:00 app[web.1]: 	at kotlinx.serialization.json.internal.AbstractJsonTreeInput.decodeSerializableValue(TreeJsonInput.kt:44)
2020-04-22T05:54:09.034074+00:00 app[web.1]: 	at kotlinx.serialization.DecodingKt.decode(Decoding.kt:521)
2020-04-22T05:54:09.034075+00:00 app[web.1]: 	at kotlinx.serialization.json.internal.TreeJsonInputKt.readJson(TreeJsonInput.kt:21)
2020-04-22T05:54:09.034075+00:00 app[web.1]: 	at kotlinx.serialization.json.Json.fromJson(Json.kt:151)
2020-04-22T05:54:09.034076+00:00 app[web.1]: 	at com.github.insanusmokrassar.TelegramBotAPI.types.buttons.InlineKeyboardButtons.InlineKeyboardButtonSerializer.deserialize(InlineKeyboardButtonSerializer.kt:31)
2020-04-22T05:54:09.034076+00:00 app[web.1]: 	at com.github.insanusmokrassar.TelegramBotAPI.types.buttons.InlineKeyboardButtons.InlineKeyboardButtonSerializer.deserialize(InlineKeyboardButtonSerializer.kt:8)
2020-04-22T05:54:09.034077+00:00 app[web.1]: 	at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:52)
2020-04-22T05:54:09.034077+00:00 app[web.1]: 	at kotlinx.serialization.json.internal.AbstractJsonTreeInput.decodeSerializableValue(TreeJsonInput.kt:44)
2020-04-22T05:54:09.034078+00:00 app[web.1]: 	at kotlinx.serialization.internal.TaggedDecoder$decodeSerializableElement$1.invoke(Tagged.kt:230)
2020-04-22T05:54:09.034078+00:00 app[web.1]: 	at kotlinx.serialization.internal.TaggedDecoder.tagBlock(Tagged.kt:243)
2020-04-22T05:54:09.034079+00:00 app[web.1]: 	at kotlinx.serialization.internal.TaggedDecoder.decodeSerializableElement(Tagged.kt:230)
2020-04-22T05:54:09.034079+00:00 app[web.1]: 	at kotlinx.serialization.internal.ListLikeSerializer.readElement(CollectionSerializers.kt:87)
2020-04-22T05:54:09.034080+00:00 app[web.1]: 	at kotlinx.serialization.internal.AbstractCollectionSerializer.readElement$default(CollectionSerializers.kt:54)
2020-04-22T05:54:09.034080+00:00 app[web.1]: 	at kotlinx.serialization.internal.AbstractCollectionSerializer.patch(CollectionSerializers.kt:36)
2020-04-22T05:54:09.034081+00:00 app[web.1]: 	at kotlinx.serialization.internal.AbstractCollectionSerializer.deserialize(CollectionSerializers.kt:45)
2020-04-22T05:54:09.034081+00:00 app[web.1]: 	at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:52)
2020-04-22T05:54:09.034082+00:00 app[web.1]: 	at kotlinx.serialization.json.internal.AbstractJsonTreeInput.decodeSerializableValue(TreeJsonInput.kt:44)
2020-04-22T05:54:09.034082+00:00 app[web.1]: 	at kotlinx.serialization.internal.TaggedDecoder$decodeSerializableElement$1.invoke(Tagged.kt:230)
2020-04-22T05:54:09.034083+00:00 app[web.1]: 	at kotlinx.serialization.internal.TaggedDecoder.tagBlock(Tagged.kt:243)
2020-04-22T05:54:09.034083+00:00 app[web.1]: 	at kotlinx.serialization.internal.TaggedDecoder.decodeSerializableElement(Tagged.kt:230)
2020-04-22T05:54:09.034084+00:00 app[web.1]: 	at kotlinx.serialization.internal.ListLikeSerializer.readElement(CollectionSerializers.kt:87)
2020-04-22T05:54:09.034084+00:00 app[web.1]: 	at kotlinx.serialization.internal.AbstractCollectionSerializer.readElement$default(CollectionSerializers.kt:54)
2020-04-22T05:54:09.034085+00:00 app[web.1]: 	at kotlinx.serialization.internal.AbstractCollectionSerializer.patch(CollectionSerializers.kt:36)
2020-04-22T05:54:09.034085+00:00 app[web.1]: 	at kotlinx.serialization.internal.AbstractCollectionSerializer.deserialize(CollectionSerializers.kt:45)
2020-04-22T05:54:09.034086+00:00 app[web.1]: 	at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:52)
2020-04-22T05:54:09.034094+00:00 app[web.1]: 	at kotlinx.serialization.json.internal.AbstractJsonTreeInput.decodeSerializableValue(TreeJsonInput.kt:44)
2020-04-22T05:54:09.034095+00:00 app[web.1]: 	at kotlinx.serialization.internal.TaggedDecoder$decodeSerializableElement$1.invoke(Tagged.kt:230)
2020-04-22T05:54:09.034095+00:00 app[web.1]: 	at kotlinx.serialization.internal.TaggedDecoder.tagBlock(Tagged.kt:243)
2020-04-22T05:54:09.034095+00:00 app[web.1]: 	at kotlinx.serialization.internal.TaggedDecoder.decodeSerializableElement(Tagged.kt:230)
2020-04-22T05:54:09.034096+00:00 app[web.1]: 	at com.github.insanusmokrassar.TelegramBotAPI.types.buttons.InlineKeyboardMarkup$$serializer.deserialize(InlineKeyboardMarkup.kt)
2020-04-22T05:54:09.034097+00:00 app[web.1]: 	at com.github.insanusmokrassar.TelegramBotAPI.types.buttons.InlineKeyboardMarkup$$serializer.deserialize(InlineKeyboardMarkup.kt:10)
2020-04-22T05:54:09.034097+00:00 app[web.1]: 	at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:52)
2020-04-22T05:54:09.034098+00:00 app[web.1]: 	at kotlinx.serialization.json.internal.AbstractJsonTreeInput.decodeSerializableValue(TreeJsonInput.kt:44)
2020-04-22T05:54:09.034101+00:00 app[web.1]: 	at kotlinx.serialization.Decoder$DefaultImpls.decodeNullableSerializableValue(Decoding.kt:231)
2020-04-22T05:54:09.034102+00:00 app[web.1]: 	at kotlinx.serialization.internal.TaggedDecoder.decodeNullableSerializableValue(Tagged.kt:153)
2020-04-22T05:54:09.034102+00:00 app[web.1]: 	at kotlinx.serialization.internal.TaggedDecoder$decodeNullableSerializableElement$1.invoke(Tagged.kt:233)
2020-04-22T05:54:09.034103+00:00 app[web.1]: 	at kotlinx.serialization.internal.TaggedDecoder.tagBlock(Tagged.kt:243)
2020-04-22T05:54:09.034103+00:00 app[web.1]: 	at kotlinx.serialization.internal.TaggedDecoder.decodeNullableSerializableElement(Tagged.kt:233)
2020-04-22T05:54:09.034104+00:00 app[web.1]: 	at com.github.insanusmokrassar.TelegramBotAPI.types.message.RawMessage$$serializer.deserialize(RawMessage.kt)
2020-04-22T05:54:09.034104+00:00 app[web.1]: 	at com.github.insanusmokrassar.TelegramBotAPI.types.message.RawMessage$$serializer.deserialize(RawMessage.kt:28)
2020-04-22T05:54:09.034105+00:00 app[web.1]: 	at com.github.insanusmokrassar.TelegramBotAPI.types.message.abstracts.TelegramBotAPIMessageDeserializationStrategyClass.deserialize(Message.kt:29)
2020-04-22T05:54:09.034105+00:00 app[web.1]: 	at com.github.insanusmokrassar.TelegramBotAPI.types.message.abstracts.TelegramBotAPIMessageDeserializeOnlySerializerClass.deserialize(Message.kt:41)
2020-04-22T05:54:09.034106+00:00 app[web.1]: 	at com.github.insanusmokrassar.TelegramBotAPI.types.message.abstracts.TelegramBotAPIMessageDeserializeOnlySerializer.deserialize(Message.kt)
2020-04-22T05:54:09.034106+00:00 app[web.1]: 	at com.github.insanusmokrassar.TelegramBotAPI.types.message.abstracts.TelegramBotAPIMessageDeserializeOnlySerializer.deserialize(Message.kt:48)
2020-04-22T05:54:09.034107+00:00 app[web.1]: 	at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:52)
2020-04-22T05:54:09.034107+00:00 app[web.1]: 	at kotlinx.serialization.json.internal.AbstractJsonTreeInput.decodeSerializableValue(TreeJsonInput.kt:44)
2020-04-22T05:54:09.034108+00:00 app[web.1]: 	at kotlinx.serialization.Decoder$DefaultImpls.decodeNullableSerializableValue(Decoding.kt:231)
2020-04-22T05:54:09.034108+00:00 app[web.1]: 	at kotlinx.serialization.internal.TaggedDecoder.decodeNullableSerializableValue(Tagged.kt:153)
2020-04-22T05:54:09.034109+00:00 app[web.1]: 	at kotlinx.serialization.internal.TaggedDecoder$decodeNullableSerializableElement$1.invoke(Tagged.kt:233)
2020-04-22T05:54:09.034109+00:00 app[web.1]: 	at kotlinx.serialization.internal.TaggedDecoder.tagBlock(Tagged.kt:243)
2020-04-22T05:54:09.034110+00:00 app[web.1]: 	at kotlinx.serialization.internal.TaggedDecoder.decodeNullableSerializableElement(Tagged.kt:233)
2020-04-22T05:54:09.034110+00:00 app[web.1]: 	at com.github.insanusmokrassar.TelegramBotAPI.types.update.RawUpdate$$serializer.deserialize(RawUpdate.kt)
2020-04-22T05:54:09.034111+00:00 app[web.1]: 	at com.github.insanusmokrassar.TelegramBotAPI.types.update.RawUpdate$$serializer.deserialize(RawUpdate.kt:20)
2020-04-22T05:54:09.034112+00:00 app[web.1]: 	at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:52)
2020-04-22T05:54:09.034112+00:00 app[web.1]: 	at kotlinx.serialization.json.internal.AbstractJsonTreeInput.decodeSerializableValue(TreeJsonInput.kt:44)
2020-04-22T05:54:09.034112+00:00 app[web.1]: 	at kotlinx.serialization.DecodingKt.decode(Decoding.kt:521)
2020-04-22T05:54:09.034113+00:00 app[web.1]: 	at kotlinx.serialization.json.internal.TreeJsonInputKt.readJson(TreeJsonInput.kt:21)
2020-04-22T05:54:09.034113+00:00 app[web.1]: 	at kotlinx.serialization.json.Json.fromJson(Json.kt:151)
2020-04-22T05:54:09.034114+00:00 app[web.1]: 	at com.github.insanusmokrassar.TelegramBotAPI.utils.extensions.WebhooksKt$setWebhook$env$1$1$1$1.invokeSuspend(Webhooks.kt:78)
2020-04-22T05:54:09.034114+00:00 app[web.1]: 	at com.github.insanusmokrassar.TelegramBotAPI.utils.extensions.WebhooksKt$setWebhook$env$1$1$1$1.invoke(Webhooks.kt)
2020-04-22T05:54:09.034115+00:00 app[web.1]: 	at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:318)
2020-04-22T05:54:09.034115+00:00 app[web.1]: 	at io.ktor.util.pipeline.SuspendFunctionGun.proceed(PipelineContext.kt:163)
2020-04-22T05:54:09.034115+00:00 app[web.1]: 	at io.ktor.util.pipeline.SuspendFunctionGun.execute(PipelineContext.kt:183)
2020-04-22T05:54:09.034116+00:00 app[web.1]: 	at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:27)
2020-04-22T05:54:09.034116+00:00 app[web.1]: 	at io.ktor.routing.Routing.executeResult(Routing.kt:147)
2020-04-22T05:54:09.034120+00:00 app[web.1]: 	at io.ktor.routing.Routing.interceptor(Routing.kt:34)
2020-04-22T05:54:09.034121+00:00 app[web.1]: 	at io.ktor.routing.Routing$Feature$install$1.invokeSuspend(Routing.kt:99)
2020-04-22T05:54:09.034121+00:00 app[web.1]: 	at io.ktor.routing.Routing$Feature$install$1.invoke(Routing.kt)
2020-04-22T05:54:09.034121+00:00 app[web.1]: 	at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:318)
2020-04-22T05:54:09.034122+00:00 app[web.1]: 	at io.ktor.util.pipeline.SuspendFunctionGun.proceed(PipelineContext.kt:163)
2020-04-22T05:54:09.034123+00:00 app[web.1]: 	at io.ktor.util.pipeline.SuspendFunctionGun.execute(PipelineContext.kt:183)
2020-04-22T05:54:09.034123+00:00 app[web.1]: 	at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:27)
2020-04-22T05:54:09.034124+00:00 app[web.1]: 	at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$2.invokeSuspend(DefaultEnginePipeline.kt:120)
2020-04-22T05:54:09.034124+00:00 app[web.1]: 	at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$2.invoke(DefaultEnginePipeline.kt)
2020-04-22T05:54:09.034125+00:00 app[web.1]: 	at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:318)
2020-04-22T05:54:09.034125+00:00 app[web.1]: 	at io.ktor.util.pipeline.SuspendFunctionGun.proceed(PipelineContext.kt:163)
2020-04-22T05:54:09.034125+00:00 app[web.1]: 	at io.ktor.util.pipeline.SuspendFunctionGun.execute(PipelineContext.kt:183)
2020-04-22T05:54:09.034126+00:00 app[web.1]: 	at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:27)
2020-04-22T05:54:09.034126+00:00 app[web.1]: 	at io.ktor.server.netty.NettyApplicationCallHandler$handleRequest$1.invokeSuspend(NettyApplicationCallHandler.kt:40)
2020-04-22T05:54:09.034127+00:00 app[web.1]: 	at io.ktor.server.netty.NettyApplicationCallHandler$handleRequest$1.invoke(NettyApplicationCallHandler.kt)
2020-04-22T05:54:09.034127+00:00 app[web.1]: 	at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:55)
2020-04-22T05:54:09.034128+00:00 app[web.1]: 	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:111)
2020-04-22T05:54:09.034128+00:00 app[web.1]: 	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:158)
2020-04-22T05:54:09.034128+00:00 app[web.1]: 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:54)
2020-04-22T05:54:09.034129+00:00 app[web.1]: 	at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
2020-04-22T05:54:09.034129+00:00 app[web.1]: 	at io.ktor.server.netty.NettyApplicationCallHandler.handleRequest(NettyApplicationCallHandler.kt:30)
2020-04-22T05:54:09.034130+00:00 app[web.1]: 	at io.ktor.server.netty.NettyApplicationCallHandler.channelRead(NettyApplicationCallHandler.kt:24)
2020-04-22T05:54:09.034130+00:00 app[web.1]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
2020-04-22T05:54:09.034130+00:00 app[web.1]: 	at io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext.java:59)
2020-04-22T05:54:09.034131+00:00 app[web.1]: 	at io.netty.channel.AbstractChannelHandlerContext$7.run(AbstractChannelHandlerContext.java:368)
2020-04-22T05:54:09.034131+00:00 app[web.1]: 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
2020-04-22T05:54:09.034131+00:00 app[web.1]: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
2020-04-22T05:54:09.034132+00:00 app[web.1]: 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
2020-04-22T05:54:09.034132+00:00 app[web.1]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
2020-04-22T05:54:09.034132+00:00 app[web.1]: 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
2020-04-22T05:54:09.034133+00:00 app[web.1]: 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
2020-04-22T05:54:09.034133+00:00 app[web.1]: 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by InsanusMokrassar** [comment]
Fixed [here](https://github.com/InsanusMokrassar/TelegramBotAPI/pull/83)
